[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.5.3",
    "celery-types>=0.23.0",
    "django>=5.2.6",
    "django-celery-beat>=2.8.1",
    "django-celery-results>=2.6.0",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.12.0",
    "django-filter>=25.1",
    "django-minio-storage>=0.5.8",
    "djangorestframework>=3.16.1",
    "drf-spectacular>=0.28.0",
    "drf-spectacular-sidecar>=2025.9.1",
    "gigachat>=0.1.42.post2",
    "gunicorn>=23.0.0",
    "markdown>=3.9",
    "minio>=7.2.16",
    "ollama>=0.5.4",
    "openai>=1.107.3",
    "pillow>=11.3.0",
    "psycopg2-binary>=2.9.10",
    "pymupdf>=1.26.4",
    "python-dotenv>=1.1.1",
    "qdrant-client>=1.15.1",
    "redis>=6.4.0",
    "regex>=2025.9.1",
    "sentence-transformers>=5.1.0",
    "split-settings>=1.0.0",
    "unicorn>=2.1.4",
    "uvicorn>=0.35.0",
]
