/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход в систему (создание сессии)
         * @description Принимает имя пользователя и пароль. При успешной аутентификации создаёт серверную сессию и возвращает минимальные данные пользователя.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход из системы (уничтожение сессии)
         * @description Завершает серверную сессию текущего пользователя. Операция идемпотентна: если пользователь не был аутентифицирован, также возвращается 204.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация пользователя
         * @description Создаёт нового пользователя по переданным данным. Пароль сохраняется в хешированном виде.
         *
         *     Аутентификация после регистрации не выполняется автоматически — используйте эндпоинт логина.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/chat/dialogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description * **GET  /api/v0/chat/dialogs**               — список диалогов
         *     * **POST /api/v0/chat/dialogs**               — создать диалог
         *     * **GET  /api/v0/chat/dialogs/{id}/message**  — история сообщений
         *     * **POST /api/v0/chat/dialogs/{id}/message**  — отправить сообщение */
        get: operations["v0_chat_dialogs_list"];
        put?: never;
        /** @description * **GET  /api/v0/chat/dialogs**               — список диалогов
         *     * **POST /api/v0/chat/dialogs**               — создать диалог
         *     * **GET  /api/v0/chat/dialogs/{id}/message**  — история сообщений
         *     * **POST /api/v0/chat/dialogs/{id}/message**  — отправить сообщение */
        post: operations["v0_chat_dialogs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/chat/dialogs/{id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Пагинированный список сообщений */
        get: operations["v0_chat_dialogs_message_retrieve"];
        put?: never;
        /** @description GET → история; POST → отправка сообщения. */
        post: operations["v0_chat_dialogs_message_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/clinical-recomendation/document/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список документов
         * @description Возвращает список загруженных документов, отсортированных по дате создания (DESC).
         */
        get: operations["v0_clinical_recomendation_document_list"];
        put?: never;
        /**
         * Загрузить документ
         * @description Загружает файл (PDF/DOCX/...), создаёт запись и ставит в очередь пайплайн парсинга/индексации.
         */
        post: operations["v0_clinical_recomendation_document_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/clinical-recomendation/document/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить документ */
        get: operations["v0_clinical_recomendation_document_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/clinical-recomendation/document/{id}/purge/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить документ и его эмбеддинги
         * @description Удаляет документ из БД и все связанные точки из Qdrant.
         */
        delete: operations["v0_clinical_recomendation_document_purge_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/clinical-recomendation/document/{id}/reindex/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Переиндексировать документ
         * @description Повторно запускает пайплайн парсинга/чанкинга/эмбеддингов/апсерта в Qdrant.
         */
        post: operations["v0_clinical_recomendation_document_reindex_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/clinical-recomendation/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поиск по эмбеддингам (vector/hybrid) в Qdrant
         * @description Ищет релевантные чанки по запросу `q`. `mode=vector` — чисто векторный поиск, `mode=hybrid` — гибридный (вектор + полнотекст, если настроен индекс). По умолчанию результаты ограничены документами текущего пользователя.
         */
        get: operations["v0_clinical_recomendation_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/field-definitions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список полей
         * @description Возвращает список полей с пагинацией.
         */
        get: operations["v0_field_definitions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/field-definitions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить поле
         * @description Возвращает одно поле по ID.
         */
        get: operations["v0_field_definitions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/semd-document-templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список шаблонов документов
         * @description Возвращает список шаблонов документов с их полями.
         */
        get: operations["v0_semd_document_templates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/semd-document-templates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить шаблон документа
         * @description Возвращает один шаблон документа по ID.
         */
        get: operations["v0_semd_document_templates_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/test_chat_api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unified chat completions (clinical & generic)
         * @description /api/test-chat/  (POST → create)
         *
         *     Настраиваемые query-параметры:
         *         mode     – 'vector' | 'hybrid'  (по умолчанию 'vector')
         *         k        – int, количество фрагментов CONTEXT (по умолчанию 5)
         *         doc_id   – int | None, фильтр документа
         *         section  – str | None, фильтр секции/главы
         */
        post: operations["v0_test_chat_api_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь
         * @description Возвращает подробные данные текущего аутентифицированного пользователя.
         *
         *     Требуется активная сессия (cookie) или другая совместимая схема аутентификации.
         */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/me/minimal/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь (минимально)
         * @description Возвращает минимальный набор данных текущего аутентифицированного пользователя.
         *
         *     Требуется активная сессия (cookie) или другая совместимая схема аутентификации.
         */
        get: operations["users_me_minimal_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatMessage: {
            readonly id: number;
            role: components["schemas"]["RoleEnum"];
            content: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ChatRequest: {
            messages: components["schemas"]["ChatMessage"][];
            /** @default false */
            stream: boolean;
            /** @description Любые параметры, поддерживаемые моделью (temperature, top_p …) */
            params?: {
                [key: string]: unknown;
            };
        };
        ChatResponse: {
            /** @description Полный ответ LLM — возвращается, если stream=false */
            answer: string;
        };
        Dialog: {
            readonly id: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
        };
        DialogCreate: {
            title?: string;
        };
        DialogSendMessage: {
            content: string;
            params?: {
                [key: string]: unknown;
            };
            /** @default false */
            stream: boolean;
        };
        DocumentOut: {
            readonly id: number;
            title?: string;
            /** Format: uri */
            file: string;
            source?: string;
            content_type?: string;
            language?: string;
            status?: components["schemas"]["StatusEnum"];
            error?: string;
            meta?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Владелец */
            owner: number;
        };
        DocumentTemplate: {
            readonly id: number;
            /**
             * Название шаблона
             * @description Название медицинского документа (например 'Эпикриз').
             */
            name: string;
            /**
             * Код шаблона
             * @description Уникальный системный идентификатор шаблона (например 'epicrisis').
             */
            slug: string;
            /**
             * Описание
             * @description Для чего предназначен данный шаблон.
             */
            description?: string;
            readonly fields: components["schemas"]["TemplateField"][];
        };
        DocumentUpload: {
            readonly id: number;
            title?: string;
            /** Format: uri */
            file: string;
            source?: string;
            language?: string;
        };
        FieldDefinition: {
            readonly id: number;
            /**
             * Ключ поля
             * @description Уникальный технический идентификатор поля в системе (например 'anamnesis').
             */
            key: string;
            /**
             * Название поля
             * @description Отображаемое название поля для пользователя (например 'Анамнез').
             */
            label: string;
            /**
             * Тип поля
             * @description Определяет, какой вид данных ожидается (текст, число, дата и т.п.).
             *
             *     * `text` - Текст
             *     * `long_text` - Длинный текст
             *     * `number` - Число
             *     * `integer` - Целое
             *     * `decimal` - Десятичное
             *     * `date` - Дата
             *     * `datetime` - Дата и время
             *     * `boolean` - Логический (да/нет)
             */
            field_type?: components["schemas"]["FieldTypeEnum"];
            /**
             * Обязательное
             * @description Если включено — поле должно быть заполнено.
             */
            required?: boolean;
            /**
             * Серверные валидаторы
             * @description Список встроенных правил проверки, например ['not_empty', 'max_length:1000'].
             */
            server_validators?: string[];
            /**
             * Варианты валидации
             * @description Каким образом проверяется поле: сервер, ИИ или обе стратегии.
             *
             *     * `none` - Нет
             *     * `server` - Серверная
             *     * `llm` - ИИ (LLM)
             *     * `both` - Обе
             */
            validation_strategy?: components["schemas"]["ValidationStrategyEnum"];
        };
        /**
         * @description * `text` - Текст
         *     * `long_text` - Длинный текст
         *     * `number` - Число
         *     * `integer` - Целое
         *     * `decimal` - Десятичное
         *     * `date` - Дата
         *     * `datetime` - Дата и время
         *     * `boolean` - Логический (да/нет)
         * @enum {string}
         */
        FieldTypeEnum: "text" | "long_text" | "number" | "integer" | "decimal" | "date" | "datetime" | "boolean";
        /** @description Простой сериализатор логина по username и password. */
        Login: {
            /** Имя пользователя */
            username: string;
            /** Пароль */
            password: string;
        };
        /** @description Минимальный сериализатор пользователя для отображения основных атрибутов.
         *
         *     Назначение:
         *     - Используется там, где нужен краткий профиль пользователя без служебных полей.
         *     - Все поля только для чтения, чтобы не допускать записи через этот сериализатор. */
        MinimalUser: {
            readonly id: number;
            /** Имя пользователя */
            readonly username: string;
            /** Имя */
            readonly first_name: string;
            /** Фамилия */
            readonly last_name: string;
            /** Отчество */
            readonly patronymic: string;
        };
        /**
         * @description * `vector` - vector
         *     * `hybrid` - hybrid
         * @enum {string}
         */
        ModeEnum: "vector" | "hybrid";
        /** @description count / next / previous / results */
        PaginatedChatMessage: {
            count: number;
            next: string | null;
            previous: string | null;
            results: components["schemas"]["ChatMessage"][];
        };
        PaginatedDialogList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Dialog"][];
        };
        PaginatedDocumentTemplateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DocumentTemplate"][];
        };
        PaginatedFieldDefinitionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["FieldDefinition"][];
        };
        /** @description Сериализатор регистрации пользователя.
         *
         *     Ожидаемые входные поля:
         *     - username: строка, обязательна
         *     - password: строка, обязательна (write-only)
         *     - first_name, last_name, patronymic: необязательные строки
         *     - position: первичный ключ существующей должности (обязателен)
         *
         *     На выходе не содержит поле `password`. */
        Register: {
            /** Имя пользователя */
            username: string;
            /** Пароль */
            password: string;
            /** Имя */
            first_name?: string;
            /** Фамилия */
            last_name?: string;
            /** Отчество */
            patronymic?: string;
            /** Должность */
            position: number;
        };
        /**
         * @description * `user` - User
         *     * `assistant` - Assistant
         *     * `system` - System
         * @enum {string}
         */
        RoleEnum: "user" | "assistant" | "system";
        SearchHit: {
            /** Format: double */
            score: number;
            doc_id: number;
            owner_id?: number;
            idx: number;
            section: string;
            page_from: number | null;
            page_to: number | null;
            text: string;
        };
        SearchResponse: {
            q: string;
            mode: components["schemas"]["ModeEnum"];
            results: components["schemas"]["SearchHit"][];
        };
        /**
         * @description * `UPLOADED` - Uploaded
         *     * `PARSED` - Parsed
         *     * `INDEXED` - Indexed
         *     * `FAILED` - Failed
         * @enum {string}
         */
        StatusEnum: "UPLOADED" | "PARSED" | "INDEXED" | "FAILED";
        TemplateField: {
            /**
             * Порядок отображения
             * @description Определяет порядок отображения поля в шаблоне.
             */
            order?: number;
            field: components["schemas"]["FieldDefinition"];
        };
        /** @description Сериализатор для представления основных полей пользователя.
         *
         *     Примечания:
         *     - Поле `position` отдаётся как первичный ключ связанной модели (по умолчанию
         *       поведения DRF для ForeignKey). При необходимости можно заменить на
         *       вложенный сериализатор или строковое представление.
         *     - Дополнительно отдаем «похожим образом» отдельные поля `position_id` и
         *       `position_name`, получая их из связанной модели `Position`.
         *     - Поле `avatar` будет сериализовано как относительный путь/URL к файлу. */
        User: {
            readonly id: number;
            /** Имя пользователя */
            readonly username: string;
            /** Имя */
            readonly first_name: string;
            /** Фамилия */
            readonly last_name: string;
            /** Отчество */
            readonly patronymic: string;
            /** Должность */
            readonly position: number;
            readonly position_id: number;
            readonly position_name: string;
            /**
             * Дата создания аккаунта
             * Format: date-time
             */
            readonly date_joined: string;
            /** Активный */
            readonly is_active: boolean;
            /** Staff */
            readonly is_staff: boolean;
            /**
             * Аватар
             * Format: uri
             */
            readonly avatar: string | null;
        };
        /**
         * @description * `none` - Нет
         *     * `server` - Серверная
         *     * `llm` - ИИ (LLM)
         *     * `both` - Обе
         * @enum {string}
         */
        ValidationStrategyEnum: "none" | "server" | "llm" | "both";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinimalUser"];
                };
            };
            /** @description Ошибки валидации входных данных */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия уничтожена (или отсутствовала) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinimalUser"];
                };
            };
            /** @description Ошибки валидации входных данных */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v0_chat_dialogs_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDialogList"];
                };
            };
        };
    };
    v0_chat_dialogs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DialogCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dialog"];
                };
            };
        };
    };
    v0_chat_dialogs_message_retrieve: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this Диалог (чат-сеанс). */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChatMessage"];
                };
            };
        };
    };
    v0_chat_dialogs_message_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Диалог (чат-сеанс). */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DialogSendMessage"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                    "text/event-stream": string;
                };
            };
        };
    };
    v0_clinical_recomendation_document_list: {
        parameters: {
            query?: {
                /** @description (опц.) Поиск по title/source (если добавите фильтрацию) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    v0_clinical_recomendation_document_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpload"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
        };
    };
    v0_clinical_recomendation_document_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Клинические рекомендации. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
        };
    };
    v0_clinical_recomendation_document_purge_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Клинические рекомендации. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v0_clinical_recomendation_document_reindex_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Клинические рекомендации. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentOut"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v0_clinical_recomendation_search_list: {
        parameters: {
            query: {
                /** @description (опц.) Фильтр по конкретному документу */
                doc_id?: number;
                /** @description Количество результатов (top-k) */
                k?: number;
                /** @description Режим поиска: vector | hybrid */
                mode?: string;
                /** @description Поисковый запрос */
                q: string;
                /** @description (опц.) Фильтр по названию/части названия раздела (payload.section) */
                section?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"][];
                };
            };
        };
    };
    v0_field_definitions_list: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество элементов на странице (по умолчанию 10) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFieldDefinitionList"];
                };
            };
        };
    };
    v0_field_definitions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Определение поля. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldDefinition"];
                };
            };
        };
    };
    v0_semd_document_templates_list: {
        parameters: {
            query?: {
                /** @description Номер страницы */
                page?: number;
                /** @description Количество элементов на странице */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentTemplateList"];
                };
            };
        };
    };
    v0_semd_document_templates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Шаблон документа. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentTemplate"];
                };
            };
        };
    };
    v0_test_chat_api_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Полный ответ LLM при «stream = false» */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                    "text/event-stream": string;
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_minimal_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinimalUser"];
                };
            };
        };
    };
}
